const experts = [
    {
        category: "therapist",
        name: "Riya Verma",
        gender: "female",
        experience: 5,
        price: 2100,
        duration: "50 mins",
        expertise: ["Anxiety disorders", "Stress management"],
        languages: ["English", "Hindi"],
        image: "femalePfp.jpg",
        nextSlot: "Today, 12:00 PM",
    },
    {
        category: "psychiatrist",
        name: "Sanjay Gupta",
        gender: "male",
        experience: 7,
        price: 3300,
        duration: "50 mins",
        expertise: ["Bipolar disorder", "Sleep disorders"],
        languages: ["English", "Hindi", "Bengali"],
        image: "malePfp.jpg",
        nextSlot: "Tomorrow, 9:00 AM",
    },
    {
        category: "psychologist",
        name: "Kavita Singh",
        gender: "female",
        experience: 6,
        price: 2700,
        duration: "50 mins",
        expertise: ["Grief & loss", "Loneliness"],
        languages: ["English", "Hindi", "Punjabi"],
        image: "femalePfp.jpg",
        nextSlot: "Today, 10:00 AM",
    },
    {
        category: "therapist",
        name: "Rohan Deshmukh",
        gender: "male",
        experience: 8,
        price: 2900,
        duration: "50 mins",
        expertise: ["Anger management", "Relationship skills"],
        languages: ["English", "Hindi", "Marathi"],
        image: "malePfp.jpg",
        nextSlot: "Tomorrow, 1:30 PM",
    },
    {
        category: "psychiatrist",
        name: "Anjali Rao",
        gender: "female",
        experience: 9,
        price: 3700,
        duration: "50 mins",
        expertise: ["Personality disorders", "Trauma"],
        languages: ["English", "Hindi", "Kannada"],
        image: "femalePfp.jpg",
        nextSlot: "Today, 4:30 PM",
    },
    {
        category: "psychologist",
        name: "Vivek Menon",
        gender: "male",
        experience: 7,
        price: 2600,
        duration: "50 mins",
        expertise: ["Overthinking", "Self improvement"],
        languages: ["English", "Hindi", "Malayalam"],
        image: "malePfp.jpg",
        nextSlot: "Tomorrow, 2:30 PM",
    },
    {
        category: "therapist",
        name: "Shreya Kapoor",
        gender: "female",
        experience: 6,
        price: 2400,
        duration: "50 mins",
        expertise: ["Life transitions", "Academic concerns"],
        languages: ["English", "Hindi", "Tamil"],
        image: "femalePfp.jpg",
        nextSlot: "Today, 5:30 PM",
    },
    {
        category: "psychiatrist",
        name: "Nitin Joshi",
        gender: "male",
        experience: 10,
        price: 3900,
        duration: "50 mins",
        expertise: ["Trauma related disorders", "Adult Autism"],
        languages: ["English", "Hindi", "Gujarati"],
        image: "malePfp.jpg",
        nextSlot: "Tomorrow, 3:00 PM",
    },
    {
        category: "psychologist",
        name: "Anita Desai",
        gender: "female",
        experience: 8,
        price: 3000,
        duration: "50 mins",
        expertise: ["Child Specialist", "Eating disorders"],
        languages: ["English", "Hindi", "Telugu"],
        image: "femalePfp.jpg",
        nextSlot: "Today, 6:30 PM",
    },
    {
        category: "therapist",
        name: "Rajiv Malhotra",
        gender: "male",
        experience: 7,
        price: 2500,
        duration: "50 mins",
        expertise: ["Communication skills", "Stress management"],
        languages: ["English", "Hindi", "Punjabi"],
        image: "malePfp.jpg",
        nextSlot: "Tomorrow, 4:30 PM",
    },
    {
        category: "psychiatrist",
        name: "Sunita Reddy",
        gender: "female",
        experience: 8,
        price: 3400,
        duration: "50 mins",
        expertise: ["Geriatric mental health", "Fertility & Pregnancy concerns"],
        languages: ["English", "Hindi", "Kannada"],
        image: "femalePfp.jpg",
        nextSlot: "Today, 7:30 PM",
    },
    {
        category: "psychologist",
        name: "Arun Sharma",
        gender: "male",
        experience: 9,
        price: 3600,
        duration: "50 mins",
        expertise: ["Work related concerns", "Parenting concerns"],
        languages: ["English", "Hindi", "Bengali"],
        image: "malePfp.jpg",
        nextSlot: "Tomorrow, 5:30 PM",
    },
];

export default experts;